// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR3dmjJzMZ4cGt4lUpoNyRR5Q11rdTX84',
    appId: '1:177739275020:web:065f2911cd245817ed0729',
    messagingSenderId: '177739275020',
    projectId: 'techogram-cpad',
    authDomain: 'techogram-cpad.firebaseapp.com',
    storageBucket: 'techogram-cpad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIG3feoisJ2bL14kZSWX8SN6ARrJmHNmA',
    appId: '1:177739275020:android:6800e16d7917c488ed0729',
    messagingSenderId: '177739275020',
    projectId: 'techogram-cpad',
    storageBucket: 'techogram-cpad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3-Iu7r10uVKmbpKfSAvaosoMOguwA3s',
    appId: '1:177739275020:ios:c20ffb82ba213bdbed0729',
    messagingSenderId: '177739275020',
    projectId: 'techogram-cpad',
    storageBucket: 'techogram-cpad.appspot.com',
    iosClientId: '177739275020-aq2l5d24tvri896hsb915f3q635t0b85.apps.googleusercontent.com',
    iosBundleId: 'com.example.techogram',
  );
}
